apiVersion: v1
data:
  POSTGRES_PASSWORD: {{ required "A valid .Values.envVariables.POSTGRES_PASSWORD entry is required!" .Values.envVariables.POSTGRES_PASSWORD| b64enc }}
kind: Secret
metadata:
  name: {{ include "simplestlab-db.fullname" . }}-dbcredentials
  labels:
    {{- include "simplestlab-db.labels" . | nindent 4 }}