apiVersion: v1
data:
  init-demo.sh: {{ required "A valid .Values.initdbScript entry is required!" .Values.initdbScript| b64enc }}
kind: Secret
metadata:
  name: {{ include "simplestlab-db.fullname" . }}-initdb
  labels:
    {{- include "simplestlab-db.labels" . | nindent 4 }}