apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplestlab-db.fullname" . }}
  labels:
    {{- include "simplestlab-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: pgdb
  selector:
    {{- include "simplestlab-db.selectorLabels" . | nindent 4 }}
