apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "simplestlab-db.fullname" . }}
  labels:
    {{- include "simplestlab-db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simplestlab-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simplestlab-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simplestlab-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: initdb-secret
        secret:
          secretName: {{ include "simplestlab-db.fullname" . }}-initdb
          optional: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "simplestlab-db.fullname" . }}-dbcredentials
                key: POSTGRES_PASSWORD
          - name: PGDATA
            value: /data/postgres
          volumeMounts:
          - name: postgresdata
            mountPath: /data
          - name: initdb-secret
            mountPath: "/docker-entrypoint-initdb.d/"
            readOnly: true          
          ports:
            - name: pgdb
              containerPort: 5432
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: pgdb
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: pgdb
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: postgresdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
