FROM stefanscherer/node-windows
ENV APPDIR /APP
WORKDIR $APPDIR

COPY app.js app.js
COPY index.html index.html
COPY package.json package.json
RUN npm install
CMD ["node.exe","app.js","3000"]
EXPOSE 3000
