apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  type: NodePort
  selector:
    app: simplestlab
    component: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000