apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: simplestlab
  labels:
      component: db
      app: simplestlab 
spec:
  clusterIP: None
  selector:
    component: db
    app: simplestlab
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: db
    - protocol: TCP
      port: 9187
      targetPort: 9187
      name: exporter