apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: simplestlab
spec:
  selector:
    app: simplestlab
    component: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000