image:
  repository: docker.io/frjaraur/simplestdb
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000
  fsGroupChangePolicy: OnRootMismatch

securityContext: {}

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}

envVariables:
  POSTGRES_PASSWORD: changeme
initdbScript: |
  #!/bin/bash
  set -e

  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE USER demo with PASSWORD 'd3m0' ;
      CREATE DATABASE demo owner demo;
      GRANT ALL PRIVILEGES ON DATABASE demo TO demo;
      \connect demo;

      CREATE TABLE IF NOT EXISTS hits
      (
        hitid serial,
        serverip varchar(15) NOT NULL,
        clientip varchar(15) NOT NULL,
        date timestamp without time zone,
        PRIMARY KEY (hitid)
      );
      ALTER TABLE hits OWNER TO demo;
  EOSQL
