apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simplestlab-lb.fullname" . }}-config
  labels:
    {{- include "simplestlab-lb.labels" . | nindent 4 }}
data: 
  nginx.conf: |
{{ .Values.nginxConfig | indent 4}}
