{
 "title": "SimplestLab",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SimplestLab Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_max_usage_bytes{namespace=\"simplestlab\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SimplestLab Seconds of CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"simplestlab\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SimplestLab Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"simplestlab\"} |= ``"
    }
   ]
  }
 ]
}