apiVersion: v1
data:
  dbhost: {{ required "A valid .Values.envVariables.dbhost entry is required!" .Values.envVariables.dbhost| b64enc }}
  dbname: {{ required "A valid .Values.envVariables.dbname entry is required!" .Values.envVariables.dbname| b64enc }}
  dbpasswd: {{ required "A valid .Values.envVariables.dbpasswd entry is required!" .Values.envVariables.dbpasswd| b64enc }}
  dbuser: {{ required "A valid .Values.envVariables.dbuser entry is required!" .Values.envVariables.dbuser| b64enc }}
kind: Secret
metadata:
  name: {{ include "simplestlab-app.fullname" . }}-appcredentials
  labels:
    {{- include "simplestlab-app.labels" . | nindent 4 }}
