replicaCount: 3

image:
  repository: docker.io/frjaraur/simplestapp
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

securityContext:
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 30Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

envVariables:
  dbhost: db
  dbname: demo
  dbpasswd: d3m0
  dbuser: demo
