stages:
  - test
  - build

validate-dockerfile:
  stage: test
  image:
    name: docker.io/hadolint/hadolint:v2.12.0-alpine
  script:
    - hadolint "${CI_PROJECT_DIR}/Dockerfile"

  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  variables:
    IMAGE: "$CI_REGISTRY_IMAGE:dev"
  before_script:
    # - |
    #   echo "-----BEGIN CERTIFICATE-----
    #   MIIFTDCCAzSgAwIBAgIUTA51lPDa2rlWCawGki5aBXa222YwDQYJKoZIhvcNAQEN
    #   BQAwPjEPMA0GA1UEChMGZ2l0bGFiMQ8wDQYDVQQLEwZnaXRsYWIxGjAYBgNVBAMT
    #   EUdpdExhYiBIZWxtIENoYXJ0MB4XDTIzMDgxOTA4MjIwMFoXDTI4MDgxNzA4MjIw
    #   MFowPjEPMA0GA1UEChMGZ2l0bGFiMQ8wDQYDVQQLEwZnaXRsYWIxGjAYBgNVBAMT
    #   EUdpdExhYiBIZWxtIENoYXJ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    #   AgEA3JWXGjk9hGYEp2NF/rf+qfRKUh+i/qkt9c0aKMKiCHaeY33wIVyDS2huwUP6
    #   XM4RJlp0ACESy7eOAySIS5bnnRijC7hRykrW7Or0benOiyS3sTRAQw9Pjod/x7FT
    #   U4MEF7mCF+nBQJNT/JGYkydBlltjtUWxTElwiBghm20rYc+LTe4ib34R0DMiCvjy
    #   /GCbQ/odv8JOuwutXcgHHqBhHY4xBQoRMMwO2C8I8aJrPHw8BqLrBDZmTEp3I/Sr
    #   xYkI+vpSAlELbVAISijD3cLAdqLIr5J7WLWu8A/5Kpy4SsAJyU+n2HKN7zSj4AH7
    #   P1qYj1oK0ncyzP6dqHh7JYLkY7jUsy3zCpCMunN+uzzNz3jQuqH9AT1IstndCPQC
    #   tH23exUNt3Jhvr0Wf5hsftThxt2q5sSZgGXqRIxNfxvgTRU24v0FrFUjSC4ycMPC
    #   Zju3nGUiMXhu3WoSRlsjV9jDcucyl0c2z8eWE1Sw7q6uEdYzOecOrvdiWeiVlfRK
    #   YSv9VSUnr1OYF+x9SW0OK9hifwsi8qLHVewWX4RUN0A3Nq5bIX07UBVuv+btBm12
    #   vrQPhP4ZONW41IcRbeA3/MHZBkuwNAlsPgehPxpBOerP4ekNRWodKXkH5t2vZLIR
    #   A+h/RBepB7x0QV4qXtT0Vw8tRUf9FsZfV7PN4Cqu3ELEzz0CAwEAAaNCMEAwDgYD
    #   VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFEA4T5abckBO
    #   r6mTH+zn7Ep4GeWCMA0GCSqGSIb3DQEBDQUAA4ICAQBJF1fZVQ8zeno+9SNrAYIr
    #   8KYB3TBf1+kPdTcR9fOYNPDNTIMUKa6yY+Bmx37Bp+nsoBtMlbGQVLMJSNNBzFFG
    #   pTxJlQQhYap9JIPSntQcSbG1kRd158+q4DL23MnZX2dUQOHVQ19wOphxD/nK1z32
    #   5f2WQdysSGUWxgztl81DdYrEmfiVLHRscoWeGIz6pOzebR5FUNZ1WqQeZEoxjHMm
    #   7bgIY6d2XFucCNEK4xvWbUMzxevDLcKuLrcepNkM58ReWL1CGZYgH18IgfgSWHUk
    #   V9yOtZjMsShxt0KtTG/BEDmVESn/dGquDZLeAtMSuNBm1nG3Y+QFY5WtqVladuo3
    #   jPThyqk3ZWI7NbiC/do4+fKFCcnvNHpwvIpd8VXH77HTO1QkSDsB5uFdOA7Gk1jp
    #   L7LpREb8RBziMqBIzDoUslO+msGnUNlezuaArJogFX9jvbNtTORbk6+0a1z6ZMsZ
    #   T4QFcvpvAt6AFwDP9RoEdvEwe1V8s9vFVC8RcyF3umNVDQJHujuzLPdFUo1qfP6E
    #   2bQRzSU9Bc6EGBkne51vmGxjzjCrkT3eTsgR4M20F2E3dVZbna1FmhjSNKuHtc3o
    #   pK2HYOfSwjqg4eTrLajM6yuDSU6X+yliCr3hb0/c/RMfmd+5jRHX8zJniI6TppmP
    #   tMy8tauKLpXY4lpHqctwow==
    #   -----END CERTIFICATE-----
    #   -----BEGIN CERTIFICATE-----
    #   MIIFnjCCA4agAwIBAgIUchrAnvcK6IegwkGAFHPD3fzExNswDQYJKoZIhvcNAQEN
    #   BQAwPjEPMA0GA1UEChMGZ2l0bGFiMQ8wDQYDVQQLEwZnaXRsYWIxGjAYBgNVBAMT
    #   EUdpdExhYiBIZWxtIENoYXJ0MB4XDTIzMDgxOTA4MjIwMFoXDTI0MDgxODA4MjIw
    #   MFowIDEeMBwGA1UEAxMVMTcyLjE4LjE1OC4yNTUubmlwLmlvMIICIjANBgkqhkiG
    #   9w0BAQEFAAOCAg8AMIICCgKCAgEAziQ3go5/r9ZhpbDe619NQxRlQ9/lf2vqP1CX
    #   fNOd0n5eKZOwuXwoT+oN9KY6l1b06hp1ZHAq9gJ5TAz53jRsISx9a1Ld3C6/MYua
    #   z4OIrZiH6XmWJLUy6ByGU8hDTi2r6J7P4fxtne8hFfrevyZRIs//EROdHyPEFRhI
    #   K1+k3sEJPei1FLBqstrDmem1JcU46q+y3uEBhywq8Nnz0570AY80b98+D0jhydlx
    #   JcRRSxwsbfneK0d6Pcms8gEjLPPYbFZ0D072TjS9m8e4OxBlKfz2T2v7/MlN7o9i
    #   /iApwaKCm0e3KLjtsxm12K1Trqd24EUjni4P0t/si1lpAIh4r/yAbfERNTaLF/uZ
    #   KRDUpQGN5seNOUSSWzxewpU9RnG6S1y77RFBxOfOMyXWUfZmF0+31Y0wdq1fxT2h
    #   4hokbO5pbgYZ4kxNBuN/lq1hCTRTq5cyC4BEPBh/0Low0VatzxWJEjRsuxMNkXei
    #   Y44ZFCDh76F6E8GAFOtkof/+N+ry5sDnXChbuzKxX6ZeYxbv9dI5VNWQW2TKirOt
    #   etU2rASjEBO9Jjc7X+Isi2GyUOzo/sRE/7YGiMwaxWtZHW+QyKdfSKk/gDj2NTpk
    #   zLbb76NieiWf3o2CEhRlVFI7zYsx2tCdE/lhngnK1iSgeoC0YC8zn9U91K8VOFMo
    #   Ym5eNCUCAwEAAaOBsTCBrjAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYB
    #   BQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUR449iUAfg8MG55mIl11SBmXo
    #   gcswHwYDVR0jBBgwFoAUQDhPlptyQE6vqZMf7OfsSngZ5YIwOQYDVR0RBDIwMIIV
    #   MTcyLjE4LjE1OC4yNTUubmlwLmlvghcqLjE3Mi4xOC4xNTguMjU1Lm5pcC5pbzAN
    #   BgkqhkiG9w0BAQ0FAAOCAgEANGubgrWbaPs4YgPk8adFANskNrfYyDO9xvHdtOFG
    #   NAee+uYruM7LmprKWG7Whfgz7iD+RaFNy4aKpJ8LnDUkaXmYSv5uitT9Oq86G3/W
    #   jdCwQpG2p9fs6+yn0lNDrCnKLkpbP5fnxYwZzuPgLWT8sXOAiIcALQ+P2/pbDSun
    #   R4tn/f4I3WwbsUZU7kCmYC5wKB5BWgj0O42weDe+SJ0yYlNiQldQRKpmXiHxy3vT
    #   M6hP5Hc/bIDH9I3OE5t7P5D91E6Kum1uG0ahWV4BBwY+/K220WzcE9R5jQ5Q3Sxy
    #   /Vz1zZXH6LkbOCHEf0836mmOGtUZei5GtX25gXgUBYd7n+ZajzMulYctOAPUVqZs
    #   Trjjj+iuxCdH1Tq0RBkbbuM06Fjnzks/LzKBGzQ7h0dDJtRbf8nGQ+qwgVvy0NLv
    #   7C3GaLo3lAjzjgw3FlXL35yypIfIG6Dbt6aNll3K+Qi7NuG7uFZhR/bqs0md//0s
    #   bchmbUPmmXEzX2RyGjorAaAwYwAkX6UhCOMR0TBVLE/N2H+kymQPoxd4dwQqrQk2
    #   Sf2k7eX0zbdZTdvdEWZQBrQQ/M0hFJFXhm0uQ2LP3ITG5y9095aZA7kYnkTmVymH
    #   O4NZFnsixCkfwFAwDvdo13Wj6RwMUI7ANFR0tbnByOj7tBbdsn1qCrHkGSqexpTn
    #   qUQ=
    #   -----END CERTIFICATE-----" >> /kaniko/ssl/certs/ca-certificates.crt
    - printf '%s\n' "${LABS_LOCAL_GITLAB_CERTIFICATE}" |sed 's/- /-\n/g; s/ -/\n-/g' | sed '/CERTIFICATE/! s/ /\n/g' >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - /kaniko/executor
     --context "${CI_PROJECT_DIR}"
     --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
     --destination "${IMAGE}"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod"

build-prod:
  extends: build
  # variables:
  #   IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  before_script:
    - printf '%s\n' "${LABS_LOCAL_GITLAB_CERTIFICATE}" |sed 's/- /-\n/g; s/ -/\n-/g' | sed '/CERTIFICATE/! s/ /\n/g' >> /kaniko/ssl/certs/ca-certificates.crt
    - export CI_REGISTRY_IMAGE="$(echo $CI_REGISTRY_IMAGE|sed -e "s|/code/|/images/|g" )"
    - export RELEASE_IMAGE="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    # Required if we use multiple repositories
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$PROJECTGROUP_USER\",\"password\":\"$PROJECTGROUP_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
  script:
    - /kaniko/executor
     --context "${CI_PROJECT_DIR}"
     --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
     --destination "${IMAGE}"
     --destination "${RELEASE_IMAGE}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
