apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: webserver